server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: awss3
  cloud:
    config:
      server:
        s3:
          bucket: ums-config-file-bucket
          label: ums-config-file
    bus:
      enabled: true
    stream:
      bindings:
        springCloudBusOutput:
          producer:
            configuration:
              value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        springCloudBusInput:
          consumer:
            configuration:
              value.deserializer: org.apache.kafka.common.serialization.ByteArraySerializer

  kafka:
    bootstrap-servers: kafka:9092
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,metrics,busrefresh
  endpoint:
    health:
      show-details: always
    env:
      keys-to-sanitize: ""
